defaults:
  - override hydra/job_logging: default
  - override hydra/launcher: basic

#hydra:
#  mode: MULTIRUN
#  job_logging: {}
#  hydra_logging: {}
#  sweeper:
#    params:
#      experiment.seed: 1, 2, 3
#      experiment.learnable_std: true, false

wandb:
  project: "deepmimic"

experiment:
  seed: 1
  task_factory:
    name: ImitationFactory
    params:
      custom_dataset_conf:
        paths:
          - /home/andy/work/gitlab/mujoco/mocap_data/npz/27_07_2026_fixed/4_merged_filtered.npz
      domain_randomization_type: DefaultRandomizer
      domain_randomization_params:
        randomize_gravity: true
        gravity_range: [9.61, 10.01]
        randomize_geom_friction_tangential: true
        geom_friction_tangential_range: [0.9, 1.1]
        randomize_geom_friction_torsional: false
        geom_friction_torsional_range: [0.004, 0.006]
        randomize_geom_friction_rolling: false
        geom_friction_rolling_range: [0.00009, 0.00011]
        randomize_geom_damping: false
        geom_damping_range: [72, 88]
        randomize_geom_stiffness: false
        geom_stiffness_range: [900, 1100]
        randomize_joint_damping: true
        joint_damping_range: [0.5, 1.5]
        randomize_joint_friction_loss: false
        joint_friction_loss_range: [0.0, 0.2]
        randomize_joint_armature: false
        joint_armature_range: [0.08, 0.12]
        randomize_base_mass: true
        base_mass_to_add_range: [-1.5, 1.5]
        randomize_com_displacement: false
        com_displacement_range: [-0.15, 0.15]
        randomize_link_mass: false
        link_mass_multiplier_range:
          root_body: [0.9, 1.1]
          other_bodies: [0.95, 1.05]
        add_joint_pos_noise: true
        joint_pos_noise_scale: 0.002
        add_joint_vel_noise: true
        joint_vel_noise_scale: 0.05
        add_gravity_noise: false
        gravity_noise_scale: 0.015
        add_free_joint_lin_vel_noise: false
        lin_vel_noise_scale: 0.1
        add_free_joint_ang_vel_noise: false
        ang_vel_noise_scale: 0.02
  env_params:
    env_name: MjxUnitreeG1Inspire
    use_mjwarp: True
    nconmax: 32000
    headless: True
    horizon: 3000
    terminal_state_type: RootPoseTrajTerminalStateHandler
    terminal_state_params:
      root_height_margin: 0.15
      root_rot_margin_degrees: 30.0
      max_root_pos_deviation: 0.3
    goal_type: GoalTrajMimic
    goal_params:
      visualize_goal: true
    control_type: ${control_config.position_control.control_type}
    control_params: ${control_config.position_control.control_params}
    reward_type: MimicReward
    reward_params:
      qpos_w_exp: 5
      qvel_w_exp: 6
      rpos_w_exp: 5
      rquat_w_exp: 10
      rvel_w_exp: 2.0
      qpos_w_sum: 0.5
      qvel_w_sum: 0.5
      rpos_w_sum: 0.5
      rquat_w_sum: 0.3
      rvel_w_sum: 0.5
      joints_for_mimic:
        - root
        - left_hip_pitch_joint
        - left_hip_roll_joint
        - left_hip_yaw_joint
        - left_knee_joint
        - left_ankle_pitch_joint
        - left_ankle_roll_joint
        - right_hip_pitch_joint
        - right_hip_roll_joint
        - right_hip_yaw_joint
        - right_knee_joint
        - right_ankle_pitch_joint
        - right_ankle_roll_joint
        - waist_yaw_joint
        - waist_roll_joint
        - waist_pitch_joint
        - left_shoulder_pitch_joint
        - left_shoulder_roll_joint
        - left_shoulder_yaw_joint
        - left_elbow_joint
        - left_wrist_roll_joint
        - left_wrist_pitch_joint
        - left_wrist_yaw_joint
        - left_thumb_1_joint
        - left_thumb_2_joint
        - left_thumb_3_joint
        - left_thumb_4_joint
        - left_index_1_joint
        - left_index_2_joint
        - left_middle_1_joint
        - left_middle_2_joint
        - left_ring_1_joint
        - left_ring_2_joint
        - left_little_1_joint
        - left_little_2_joint
        - right_shoulder_pitch_joint
        - right_shoulder_roll_joint
        - right_shoulder_yaw_joint
        - right_elbow_joint
        - right_wrist_roll_joint
        - right_wrist_pitch_joint
        - right_wrist_yaw_joint
        - right_thumb_1_joint
        - right_thumb_2_joint
        - right_thumb_3_joint
        - right_thumb_4_joint
        - right_index_1_joint
        - right_index_2_joint
        - right_middle_1_joint
        - right_middle_2_joint
        - right_ring_1_joint
        - right_ring_2_joint
        - right_little_1_joint
        - right_little_2_joint
      sites_for_mimic:
        - upper_body_mimic
        - left_hand_mimic
        - left_foot_mimic
        - right_hand_mimic
        - right_foot_mimic
        - left_thumb_mimic
        - left_index_mimic
        - left_middle_mimic
        - left_ring_mimic
        - left_little_mimic
        - right_thumb_mimic
        - right_index_mimic
        - right_middle_mimic
        - right_ring_mimic
        - right_little_mimic
      finger_w_sum: 0.4
      finger_qpos_w_exp: 20
      finger_qvel_w_exp: 2
      finger_rpos_w_exp: 10
      finger_rquat_w_exp: 20
      finger_rvel_w_exp: 0.5
      finger_joints_for_mimic:
        - left_thumb_1_joint
        - left_thumb_2_joint
        - left_thumb_3_joint
        - left_thumb_4_joint
        - left_index_1_joint
        - left_index_2_joint
        - left_middle_1_joint
        - left_middle_2_joint
        - left_ring_1_joint
        - left_ring_2_joint
        - left_little_1_joint
        - left_little_2_joint
        - right_thumb_1_joint
        - right_thumb_2_joint
        - right_thumb_3_joint
        - right_thumb_4_joint
        - right_index_1_joint
        - right_index_2_joint
        - right_middle_1_joint
        - right_middle_2_joint
        - right_ring_1_joint
        - right_ring_2_joint
        - right_little_1_joint
        - right_little_2_joint
      finger_sites_for_mimic:
        - left_thumb_mimic
        - left_index_mimic
        - left_middle_mimic
        - left_ring_mimic
        - left_little_mimic
        - right_thumb_mimic
        - right_index_mimic
        - right_middle_mimic
        - right_ring_mimic
        - right_little_mimic
  hidden_layers: [512, 256]
  lr: 1e-4
  num_envs: 2048
  num_steps: 200
  total_timesteps: 500e6
  update_epochs: 4
  proportion_env_reward: 0.0
  num_minibatches: 32
  gamma: 0.99
  gae_lambda: 0.95
  clip_eps: 0.2
  init_std: 0.1
  learnable_std: true
  ent_coef: 0.003
  vf_coef: 0.5
  max_grad_norm: 0.5
  activation: tanh
  anneal_lr: true
  weight_decay: 0.0
  normalize_env: true
  debug: false
  n_seeds: 1  # will automatically take seeds from seed to seed+n_seeds
  vmap_across_seeds: true
  validation:
    active: true
    num_steps: 300
    num_envs: 100
    num: 10 # set to 0 to disable validation
    # if none of the following is set, only the mean reward and episode length is logged
    quantities: # quantities to be used for the distance measures below
      - JointPosition
      - JointVelocity
      - RelSitePosition
      - RelSiteVelocity
      - RelSiteOrientation
    measures:
      - EuclideanDistance
      - DynamicTimeWarping
      - DiscreteFrechetDistance
    rel_site_names:
      - upper_body_mimic
      - left_hand_mimic
      - left_foot_mimic
      - right_hand_mimic
      - right_foot_mimic
      - left_thumb_mimic
      - left_index_mimic
      - left_middle_mimic
      - left_ring_mimic
      - left_little_mimic
      - right_thumb_mimic
      - right_index_mimic
      - right_middle_mimic
      - right_ring_mimic
      - right_little_mimic
    joints_to_ignore:
      - pelvis_tx
      - pelvis_tz
      - pelvis_ty
      - pelvis_tilt
      - pelvis_list
      - pelvis_rotation

# Define control subconfigs
# G1 (Inspire hands) actuator order: 12 leg (L hip p/r/y, L knee, L ankle p/r,
# R hip p/r/y, R knee, R ankle p/r), 3 waist (yaw/roll/pitch), 4 L arm
# (shoulder p/r/y, elbow), 3 L wrist, 12 L fingers, 4 R arm, 3 R wrist, 12 R fingers.
control_config:
  position_control:
    control_type: DefaultControl
    control_params:
      center_on_default_pose: true

  torque_control:
    control_type: DefaultControl
    control_params: